version: "3.8"
services:
  rvc0:
    image: mitchsayre/rvc:latest
    container_name: rvc0
    volumes:
      - ./shared/weights:/app/assets/weights
      - ./shared:/app/shared
      - ./start.sh:/app/start.sh
      - ./tmp-rvc-0:/tmp/gradio
      # - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
    ports:
      - 7865:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # command: [ "/bin/bash", "start.sh" ]

  rvc1:
    image: mitchsayre/rvc:latest
    container_name: rvc1
    volumes:
      - ./shared/weights:/app/assets/weights
      - ./shared:/app/shared
      - ./start.sh:/app/start.sh
      - ./tmp-rvc-1:/tmp/gradio
      # - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
    ports:
      - 7866:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # command: [ "/bin/bash", "start.sh" ]

  rvc2:
    image: mitchsayre/rvc:latest
    container_name: rvc2
    volumes:
      - ./shared/weights:/app/assets/weights
      - ./shared:/app/shared
      - ./start.sh:/app/start.sh
      - ./tmp-rvc-2:/tmp/gradio
      # - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
    ports:
      - 7867:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # command: [ "/bin/bash", "start.sh" ]

  nisqa:
    build: ../packages/NISQA
    container_name: nisqa
    volumes:
      - ./shared:/app/shared
    ports:
      - 5240:5239
