mutation CreateAIHubVoiceModel2($input: CreateAIHubVoiceModelInput!) {
  createAIHubVoiceModel(input: $input) {
    id
    name
    version
    filename
    downloadCount
    derivedModelId
    creatorText
  }
}
