mutation CreateAIHubVoiceModel($input: CreateAIHubVoiceModelInput!) {
  createAIHubVoiceModel(input: $input) {
    id
    name
    version
    filename
    downloadCount
    derivedModelId
    creatorText
  }
}

mutation CreateVoiceModelBackupUrl($input: CreateVoiceModelBackupUrlInput!) {
  createVoiceModelBackupUrl(input: $input) {
    id
    url
    voiceModelId
  }
}
