mutation CreateAIHubVoiceModel($input: CreateAIHubVoiceModelInput!) {
  createAIHubVoiceModel(input: $input) {
    id
    name
    version
    filename
    downloadCount
    derivedModelId
    creatorText
  }
}

mutation CreateVoiceModelBackupUrl($input: CreateVoiceModelBackupUrlInput!) {
  createVoiceModelBackupUrl(input: $input) {
    id
    url
    voiceModelId
  }
}

mutation CreateVoiceModelProfile($input: CreateVoiceModelProfileInput!) {
  createVoiceModelProfile(input: $input) {
    id
    name
    voiceModelId
  }
}

mutation CreateVoiceModel($input: CreateVoiceModelInput!) {
  createVoiceModel(input: $input) {
    checksumMD5ForAdded
    checksumMD5ForWeights
    checksumSHA256ForAdded
    checksumSHA256ForWeights
    filesizeForWeights
    filesizeForAdded
    hidden
    id
    name
    processed
  }
}

mutation UpdateAIHubVoiceModel($input: UpdateAIHubVoiceModelInput!) {
  updateAIHubVoiceModel(input: $input) {
    checksumMD5ForWeights
    creatorText
    derivedModelId
    downloadCount
    filename
    id
    name
    version
  }
}

query AIHubVoiceModels($after: String) {
  AIHubVoiceModels(first: 100, minDownloadCount: 75, after: $after) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      node {
        downloadCount
        filename
        name
        checksumMD5ForWeights
        inferredProfile {
          accent
          confidence
          fictional
          gender
          id
          modelTrainedOnEnglishProbability
          name
          nativeLanguage
          relevantTags
          voiceModelId
        }
        backupUrls(first: 20) {
          edges {
            node {
              id
              url
              voiceModelId
            }
          }
        }
      }
    }
  }
}

query AIHubVoiceModelUsingChecksumMD5ForWeights($checksumMD5ForWeights: String) {
  AIHubVoiceModel(checksumMD5ForWeights: $checksumMD5ForWeights) {
    creatorText
    downloadCount
    id
    filename
    name
    version
    derivedModelId
    checksumMD5ForWeights
    inferredProfile {
      accent
      confidence
      fictional
      gender
      id
      modelTrainedOnEnglishProbability
      name
      nativeLanguage
      relevantTags
      voiceModelId
    }
  }
}
